apiVersion: apps/v1
kind: Deployment
metadata:
  name: udapeople
  labels:
    app: udapeople
spec:
  selector:
    matchLabels:
      app: udapeople
  replicas: 2
  template:
    metadata:
      labels:
        app: udapeople
    spec:
      containers:
      - name: app
        image: DOCKER_IMAGE_NAME
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
        ports:
        - containerPort: 3030