apiVersion: v1
kind: Service
metadata:
  name: udapeople
  labels:
    app: udapeople
spec:
  # automatically create an external load-balanced IP for the service.
  type: LoadBalancer
  ports:
  - port: 3030
    targetPort: 3030
    protocol: TCP
  selector:
    app: udapeople